### ISSUE TITLE
JavaScript does not actually support named parameters

### ISSUE THREAD

**Issue by weaverba137** [desihub/prospect#45]
As far as I can tell, JavaScript does not support named parameters, which means that the functions defined in `smooth_data.js` are broken.  Please correct me if I am wrong.

**Comment by armengau** [comment]
Indeed I realise that named parameters is not standard JS, at least !!

While implementing this heresy, I tried on https://www.w3schools.com/js/tryit.asp?filename=tryjs_function_return, and it seemed to work. What is even stranger is that the functions with named parameters in smooth_data.js *worked* ... with bokeh 1.3: to my understanding this issue appeared after switching to bokeh 2.1.

The correction you brought within the branch specutils apparently works fine.
In order not to depend on the branch merging, I implemented it word for word in my own branch scripts_n_doc, to be able to create html pages for target reinspection now.

So, for me this bug is fixed

**Comment by weaverba137** [comment]
At this point it would be better to actually merge the PR, rather than risk creating new merge conflicts.

**Comment by armengau** [comment]
It's ok for me to merge now, I just thought you were waiting for Stephen's review.

Thanks for spotting that bug. Just yesterday evening I ran prospect ("old" version) with bokeh 2.1 for the first time, and indeed found it did not work (pbl with ivar_in in the console log...) I don't know if I would have easily found the bug by myself.

**Comment by weaverba137** [comment]
I'm hoping Stephen can look at that today.

**Comment by sbailey** [comment]
Please proceed without me; both of your are much more up-to-speed on Prospect than me at this point and don't need to wait for my review/approvals.  Please do update it as needed to work with bokeh 2.1.  Thanks.

**Comment by weaverba137** [comment]
Fixed in #43.
