### ISSUE TITLE
Offset model to prevent obscuring spectrum.

### ISSUE THREAD

**Issue by tamarastro** [desihub/prospect#62]
Currently the Redrock model overplots the spectrum, which can obscure the lines.  When the lines are narrow it is very hard to tell whether there is actually a line underneath the model.  Can we please offset the model so it lies below the true spectrum?  (Same for the "other" models.)

**Comment by armengau** [comment]
I tried to fix that (a long, long time ago).
- We don't want to (y-)offset the model since it most often represents a (redrock) fit so should be compared directly to data
- Tried to have the data curve overlaid on top of all other curves. But then the model is often completely invisible (because of the noise in the spectra, especially if no smoothing is applied)
- We now have the possibility to click on caption labels, to set on/off any curve, so I think that solves the problem.
