### ISSUE TITLE
new quasar templates

### ISSUE THREAD

**Issue by abrodze** [desihub/prospect#77]
The quasar template in Redrock was replaced with a high and low redshift subtype: https://github.com/desihub/redrock-templates/pull/10
prospect_pages is hardcoded to find the quasar templates without a subtype so it fails with the updated templates

**Comment by sbailey** [comment]
Thanks for creating a ticket about this.  Please post an example command with filepaths of running it with redrock-templates/0.8 and what traceback you get.

Two potential issues:
1. how prospect finds a "typical quasar" to overlay on any target.
2. how prospect generates the best fit model for a specific QSO target given the redrock SPECTYPE+SUBTYPE+COEFF, now that QSOs also have a subtype.

I know (1) is a problem, but I'm not sure about (2).

For (1), the suggested fix from our discussions is for prospect itself to own reference spectra for galaxy, quasar, stars (possibly several subtypes) rather than it relying upon the 0th eigenvector from redrock templates for that.

**Comment by armengau** [comment]
For (1) I agree, the best is to have a few files (eg. ascii: lambda_rest, flux) with "Reference spectra". I actually tested this with an LBG reference spectrum, just did not have time/priority yet to implement this completely for all spectra.
For (2), in principle should already be ok (nothing was hardcoded except the number of basis elements per model = 10). Prospect was already run from different redrock versions (LBG again).

I have started a branch https://github.com/desihub/prospect/tree/manage_templates
- With this branch as it is now, running prospect on the new redrock-QSO should be ok, *but I have to test it*. However there will be no "standard QSO" to overlay on spectra.
- I'd like to implement (1) also within this branch. I cannot do it in the coming days, but should be done next week.

Note, to run prospect from previous "rrdetails/redrock" files, doing the `module swap redrock-templates/0.7.2` is mandatory.

**Comment by abrodze** [comment]
The commands below use redrock output files from before the QSO subtypes were updated from ("high redshift","low redshift") to ("HIZ","LOZ") but the logic is the same. $templatedir is identical to redrock-templates/0.8 except the subtypes for QSO

`DATA_PATH=/global/cfs/cdirs/desi/users/rongpu/redux/guadalupe/cumulative_new_qso_templates`
`OUTPUT_DIR=/global/cfs/cdirs/desi/users/abrodze/QSOtemplates/VIpages/newtemps`
`templatedir=/global/cfs/cdirs/desi/users/abrodze/4vecModel_oldFormat`
`prospect_pages --datadir ${DATA_PATH} --dirtree_type cumulative --tiles 1000 --petals 0 --with_zcatalog 
--with_multiple_model --template_dir ${templatedir} --outputdir ${OUTPUT_DIR}`

error message: `KeyError: ('QSO', )` 
triggers on line 196 of prospect/viewer/__init__.py

**Comment by armengau** [comment]
The branch https://github.com/desihub/prospect/tree/manage_templates is now almost ready to be merged, I've done all relevant tests.
The code handles this redrock template issue, and now uses "standard templates" independently of redrock.

It remains to choose these "standard templates". As of now I've just included the old templates, computed from old redrock template's 0th eigenvectors (GALAXY / QSO / STAR_F).
- I will get a new QSO template from Allyson
- I will also probably get a LYAE/LBG template from Saclay people soon
- @sbailey What about galaxy / star templates ? Those at hand from redrock are ok, but maybe other templates could be better for the purpose of VI ? Just let me know if you or someone else in the collaboration has one, it is now instantaneous to add them to prospect. The only condition is, since in the end the template info goes to the html pages, we should not add too many data (not too many templates, limited sampling).

**Comment by armengau** [comment]
Solved by https://github.com/desihub/prospect/pull/78
